import crypto from 'node:crypto';
const json=(status,body,headers={})=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
const b64=v=>Buffer.from(typeof v==='string'?v:JSON.stringify(v)).toString('base64url');
const unb64=v=>Buffer.from(v,'base64url').toString('utf8');
const secret=()=>process.env.SESSION_SECRET||'';
const sign=v=>crypto.createHmac('sha256',secret()).update(v).digest('base64url');
function users(){try{return JSON.parse(process.env.PILOT_USERS||'[]')}catch{return[]}}
function cookie(request){return Object.fromEntries((request.headers.get('cookie')||'').split(';').map(v=>v.trim().split(/=(.*)/s).slice(0,2)).filter(x=>x[0]))}
function session(request){try{const token=cookie(request).oa_session;if(!token||!secret())return null;const[p,s]=token.split('.');if(!crypto.timingSafeEqual(Buffer.from(sign(p)),Buffer.from(s)))return null;const data=JSON.parse(unb64(p));if(data.exp<Date.now())return null;return data}catch{return null}}
function sessionCookie(user){const payload=b64({username:user.username,name:user.name,role:user.role||'agent',agentCode:user.agentCode||'',exp:Date.now()+12*60*60*1000});return `oa_session=${payload}.${sign(payload)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=43200`}
let tokenCache={token:'',expires:0};
async function googleToken(){if(tokenCache.expires>Date.now()+60000)return tokenCache.token;const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=(process.env.GOOGLE_PRIVATE_KEY||'').replace(/\\n/g,'\n');if(!email||!key)throw new Error('Collegamento Google non configurato');const now=Math.floor(Date.now()/1000),head=b64({alg:'RS256',typ:'JWT'}),claim=b64({iss:email,scope:'https://www.googleapis.com/auth/spreadsheets',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600});const signature=crypto.sign('RSA-SHA256',Buffer.from(`${head}.${claim}`),key).toString('base64url');const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:`${head}.${claim}.${signature}`})});const d=await r.json();if(!r.ok)throw new Error('Autorizzazione Google non riuscita');tokenCache={token:d.access_token,expires:Date.now()+Number(d.expires_in)*1000};return tokenCache.token}
async function sheets(path,opt={}){const token=await googleToken(),r=await fetch('https://sheets.googleapis.com/v4/spreadsheets/'+path,{...opt,headers:{authorization:`Bearer ${token}`,'content-type':'application/json',...(opt.headers||{})}}),d=await r.json();if(!r.ok)throw new Error(d.error?.message||'Errore Google Fogli');return d}
const registerId=()=>process.env.REGISTER_SPREADSHEET_ID||'1N6ZcGa2r6Qc4KzkIIUg7cgfhkMajMnippGg6U_fx2Z4';
const companyId=()=>process.env.COMPANY_SPREADSHEET_ID||'1mnW70V3qcnc5nOeIMeLb5tANSl8VeDBi9Awn4H9qSJ0';
async function readRange(id,range){const q=encodeURIComponent(range);return (await sheets(`${id}/values/${q}?majorDimension=ROWS`)).values||[]}
async function append(id,range,values){return sheets(`${id}/values/${encodeURIComponent(range)}:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`,{method:'POST',body:JSON.stringify({values})})}
function objects(rows){const h=rows[0]||[];return rows.slice(1).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]??''])))}
async function ensureHeader(tab,headers){const current=await readRange(registerId(),`${tab}!A1:Z1`);if(!current.length)await append(registerId(),`${tab}!A1`,[headers])}
const companyKeys={AZ001:'companyName',AZ002:'displayName',AZ003:'vatNumber',AZ004:'taxCode',AZ005:'address',AZ006:'postalCode',AZ007:'city',AZ008:'province',AZ009:'country',AZ010:'email',AZ011:'pec',AZ012:'phone',AZ013:'website',AZ014:'sdiCode',AZ015:'iban',AZ016:'logoFileName',AZ017:'footerText',AZ018:'legalNotes',AZ019:'currency',AZ020:'defaultVat',AZ021:'offerValidityDays',AZ022:'ordersEmail'};
async function company(){const rows=await readRange(companyId(),`'Dati azienda'!A7:D40`),out={};for(const r of rows)if(companyKeys[r[0]])out[companyKeys[r[0]]]=String(r[3]??'').replace(/^"|"$/g,'');return out}
const headers=['id','number','submitted_at','updated_at','agent_code','agent_name','customer_id','customer_name','total','currency','status','version','payload_json'];
async function list(tab,user){await ensureHeader(tab,headers);let rows=objects(await readRange(registerId(),`${tab}!A1:M1000`));if(user.role!=='admin'&&user.role!=='area_head')rows=rows.filter(x=>x.agent_code===user.agentCode);return rows.map(x=>tab==='Offerte'?{...x,offer_number:x.number}:{...x,order_number:x.number})}
async function create(tab,body,user){await ensureHeader(tab,headers);const number=body.offerNumber||body.orderNumber,id=body.id||crypto.randomUUID();if(!number||!body.customerName)return json(400,{error:'Dati incompleti'});const now=new Date().toISOString(),row=[id,number,now,now,user.agentCode||body.agentCode,user.name||body.agentName,body.customerId||'',body.customerName,Number(body.total)||0,'EUR','submitted',1,JSON.stringify(body.payload||{})];await append(registerId(),`${tab}!A:M`,[row]);return json(201,{ok:true,id,number})}
export default async(request,context)=>{try{const url=new URL(request.url),path=(context.params?.splat||url.pathname.split('/api/')[1]||'').replace(/^\/+|\/+$/g,'');if(path==='login'&&request.method==='POST'){const body=await request.json(),user=users().find(x=>x.username===body.username&&x.password===body.password);if(!user)return json(401,{error:'Credenziali non valide'});return json(200,{ok:true},{'set-cookie':sessionCookie(user)})}if(path==='logout')return json(200,{ok:true},{'set-cookie':'oa_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0'});const user=session(request);if(!user)return json(401,{error:'Accesso non autorizzato'});if(path==='session')return json(200,{user});if(path==='settings'&&request.method==='GET')return json(200,{settings:{company_profile:await company()},canEdit:user.role==='admin'});if(path==='offers'&&request.method==='GET')return json(200,{offers:await list('Offerte',user),user});if(path==='orders'&&request.method==='GET')return json(200,{orders:await list('Ordini',user),user});if(path==='offers'&&request.method==='POST')return create('Offerte',await request.json(),user);if(path==='orders'&&request.method==='POST')return create('Ordini',await request.json(),user);return json(404,{error:'Servizio non disponibile'})}catch(error){console.error(error);return json(500,{error:error instanceof Error?error.message:'Errore inatteso'})}};

